In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('Advertising.csv')

In [4]:
X = df.drop('sales', axis=1)

In [5]:
y = df['sales']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynominal_converter = PolynomialFeatures(degree=3, include_bias=False)

In [8]:
poly_features = polynominal_converter.fit_transform(X)

In [9]:
poly_features.shape

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
X_train.shape

(140, 19)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

StandardScaler()

In [16]:
scaled_X_train = scaler.transform(X_train)

In [17]:
scaled_X_test = scaler.transform(X_test)

In [18]:
scaled_X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [19]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [20]:
# Study Ridge-regression L2

In [21]:
from sklearn.linear_model import Ridge

In [22]:
ridge_model = Ridge(alpha=10)

In [63]:
ridge_model.fit(scaled_X_train, y_train)

Ridge(alpha=10)

In [64]:
test_predictions = ridge_model.predict(scaled_X_test)

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [65]:
MAE = mean_absolute_error(y_test, test_predictions)

In [66]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [67]:
MAE

0.5774404204714171

In [68]:
RMSE

0.8946386461319674

In [69]:
from sklearn.linear_model import RidgeCV

In [70]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0))

In [71]:
ridge_cv_model.fit(scaled_X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]))

In [72]:
# What alpha is perform best
ridge_cv_model.alpha_

0.1

In [36]:
from sklearn.metrics import SCORERS

In [38]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [73]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [74]:
ridge_cv_model.fit(scaled_X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [75]:
ridge_cv_model.alpha_

0.1

In [76]:
test_predictions = ridge_cv_model.predict(scaled_X_test)

In [77]:
MAE = mean_absolute_error(y_test, test_predictions)

In [78]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [79]:
MAE

0.427377488434342

In [80]:
RMSE

0.6180719926962752

In [81]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [48]:
# LASSO

In [50]:
from sklearn.linear_model import LassoCV

In [88]:
#lasso_cv_model = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=1000000)
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)

In [89]:
lasso_cv_model.fit(scaled_X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [90]:
# particular alpha (or lambda in formulas)
lasso_cv_model.alpha_

0.49430709092258285

In [91]:
test_predictions = lasso_cv_model.predict(scaled_X_test)

In [92]:
MAE = mean_absolute_error(y_test, test_predictions)

In [93]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [94]:
MAE

0.6541723161252858

In [95]:
RMSE

1.130800102276254

In [96]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [97]:
from sklearn.linear_model import ElasticNetCV

In [99]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=1000000)

In [100]:
elastic_model.fit(scaled_X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [102]:
elastic_model.l1_ratio_

1.0

In [103]:
test_predictions = elastic_model.predict(scaled_X_test)

In [104]:
MAE = mean_absolute_error(y_test, test_predictions)

In [105]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [106]:
MAE

0.43350346185900673

In [107]:
RMSE

0.6063140748984032

In [108]:
elastic_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])